Expiry date
sigstore/sget-rs pull request #31
Opened 2021-11-10 19:15 UTC by jyotsna-penumaka

Resolves #12 

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2021-11-10 21:20 UTC, lkatalin approved these changes
LGTM!

2021-11-10 21:47 UTC, asraa reviewed
Beautiful!!!!

2021-11-10 21:47 UTC, asraa commented on src/policy.rs
> +    let duration = expiry.signed_duration_since(current);
should we move this into a ValidateExpires function?

2021-11-11 14:20 UTC, jyotsna-penumaka commented on src/policy.rs
> +    let duration = expiry.signed_duration_since(current);
That's a great idea.
I will make that change now.

2021-11-11 14:42 UTC, asraa requested changes

2021-11-11 14:42 UTC, asraa commented on src/policy.rs
> +fn validate_expires(contents: String) -> chrono::Duration {
sorry one more nit: maybe the param should be a policy? so we can

```
 let policy: Policy = serde_json::from_str(&contents).unwrap();
 let duration = validate_expires(policy);
 assert_eq!(duration.to_std().is_err(), false);)
 // run other validations on policy (and not re-parse)
```

2021-11-11 15:57 UTC, jyotsna-penumaka commented on src/policy.rs
> +fn validate_expires(contents: String) -> chrono::Duration {
sounds good!

2021-11-11 17:32 UTC, asraa approved these changes
Thanks!!

2021-11-11 20:05 UTC, lukehinds commented
sorry @jyotsna-penumaka just need a rebase!

2021-11-11 20:05 UTC, lukehinds approved these changes

2021-11-12 18:03 UTC, merged

2021-11-23 20:57 UTC, imjasonh commented
I get an error with `cargo build` and `cargo run` with this change, since `validate_expires` isn't used except in tests (`cargo test` works). Is there more work planned here to wire this up to the rest of the `sget` CLI? Anything I can help with?