Verify the root policy
sigstore/sget-rs pull request #42
Opened 2021-11-30 20:42 UTC by jyotsna-penumaka

Resolves #10 
Signed-off-by: jyotsna-penumaka <jpenumak@redhat.com>

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2021-11-30 21:54 UTC, lkatalin requested changes
This looks great! Inline I had some suggestions about using the `CosignVerificationKey` type and getting rid of some `unwrap()`s. In general, the only places we want to use `unwrap()`s are in tests (because they don't return a `Result`) or with `Option` types (where you have no better choice).

2021-11-30 21:54 UTC, lkatalin commented on src/policy.rs
> +    pub fn extract_pub_key(&self) -> Result<VerifyingKey<p256::NistP256>, anyhow::Error> {
Since you made the `CosignVerificationKey` type for this, it would be good to use it in the `Result<>`.

2021-11-30 21:54 UTC, lkatalin commented on src/policy.rs
> +        let cert = base64::decode(&self.signatures[0].cert).unwrap(); //#[allow_ci]
Since this function returns a `Result`, you should be able to use the `?` operator instead of `unwrap()` here. Though you may have to coerce it into the correct error type.

2021-11-30 21:54 UTC, lkatalin commented on src/policy.rs
> +    #[cfg(not(target_os = "windows"))]
Would you make a note on the open issue about getting tests to run on Windows that this is another one we should figure out?

2021-11-30 22:07 UTC, jyotsna-penumaka commented on src/policy.rs
> +        let cert = base64::decode(&self.signatures[0].cert).unwrap(); //#[allow_ci]
Thanks for the suggestion.
Thats a great idea!

2021-11-30 22:07 UTC, jyotsna-penumaka commented on src/policy.rs
> +    pub fn extract_pub_key(&self) -> Result<VerifyingKey<p256::NistP256>, anyhow::Error> {
Oh yes, that would make more sense.
Thank you!

2021-11-30 22:09 UTC, jyotsna-penumaka commented on src/policy.rs
> +    #[cfg(not(target_os = "windows"))]
:+1:

2021-11-30 23:18 UTC, lkatalin approved these changes
LGTM! I'm not sure why clippy is stuck (not your fault, something with GHA). Maybe it will get unstuck and then we can merge.

2021-12-01 18:11 UTC, lkatalin commented
@lukehinds @imjasonh Any ideas why the clippy test would be stuck? Do we have a clippy test in our workflow? This [link](https://github.community/t/expected-waiting-for-status-to-be-reported/18001/2) suggests not having one could be a cause. I'm seeing a command to add clippy but not seeing one to actually run it [here](https://github.com/sigstore/sget/blob/main/.github/workflows/main.yml#L42). But I'm also not extremely familiar with the GH workflows. I've already tried to re-trigger the jobs, but it got stuck again.

2021-12-01 18:23 UTC, lukehinds commented
I removed it from the branch protection, but can't clear the job

@jyotsna-penumaka can you push the following to this branch:

`git commit --allow-empty -m "Trigger Build"`

2021-12-02 22:48 UTC, lkatalin commented
I fixed the hanging clippy test by deleting it from branch protections altogether. We do want it enabled, though... I'll make sure there's an issue for it.

2021-12-02 22:48 UTC, merged